USE bbdd;
DROP TABLE IF EXISTS Prod_Comprador;
DROP TABLE IF EXISTS Prod_Tienda;
DROP TABLE IF EXISTS Compradores;
DROP TABLE IF EXISTS Tiendas;
DROP TABLE IF EXISTS Productos;
DROP TABLE IF EXISTS Mensajes;